# docker-compose.yml
version: "3.3"
services:
  database:
    image: postgres:13
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql
    ports:
      - 5432:5432
  migration:
    build: .
    command: eval Domain.Migration.migrate
    env_file:
      - app.env
    depends_on:
      - database
  #app:
  #  build: .
  #  command: start
  #  env_file:
  #    - app.env
  #  ports:
  #    - 8080:8080
  #  depends_on:
  #    - migration
volumes:
  database-data:
